#:schema node_modules/wrangler/config-schema.json

workers_dev = true
name = "rr7-cloudflare-workers"
main = "./workers/app.ts"

# Compatibility
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

# Assets
assets = { directory = "./build/client/" }

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"
